/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "var(--on-error-container)",
        "surface-container": "var(--surface-container)",
        tertiary: "var(--tertiary)",
        "on-secondary": "var(--on-secondary)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "outline-variant": "var(--outline-variant)",
        "surface-dim": "var(--surface-dim)",
        "error-container": "var(--error-container)",
        "secondary-container": "var(--secondary-container)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface-variant": "var(--surface-variant)",
        "on-background": "var(--on-background)",
        "primary-container": "var(--primary-container)",
        surface: "var(--surface)",
        "on-tertiary": "var(--on-tertiary)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "inverse-surface": "var(--inverse-surface)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-primary-container": "var(--on-primary-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "surface-container-low": "var(--surface-container-low)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "tertiary-container": "var(--tertiary-container)",
        "on-error": "var(--on-error)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-primary": "var(--on-primary)",
        "surface-container-high": "var(--surface-container-high)",
        "on-surface": "var(--on-surface)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "primary-fixed": "var(--primary-fixed)",
        primary: "var(--primary)",
        "surface-tint": "var(--surface-tint)",
        error: "var(--error)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-surface-variant": "var(--on-surface-variant)",
        background: "var(--background)",
        secondary: "var(--secondary)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-bright": "var(--surface-bright)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "inverse-primary": "var(--inverse-primary)",
        outline: "var(--outline)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "display": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
